name: flwr-niid-bench
channels:
  - conda-forge
  - defaults
  - sebp
dependencies:
  - python=3.10.6
  - scikit-learn
  - matplotlib
  - seaborn
prefix: C:\Users\AFreitas\AppData\Local\anaconda3\envs\flwr-niid-bench
