name: flwr-niid-bench
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.1.0
  - bzip2=1.0.8
  - ca-certificates
  - cairo
  - contourpy
  - cycler
  - double-conversion
  - fontconfig
  - fonttools
  - freetype
  - harfbuzz
  - icu
  - joblib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libdeflate
  - libexpat
  - libffi
  - libglib
  - libiconv
  - libjpeg-turbo
  - liblapack
  - liblzma
  - libpng
  - libsqlite
  - libtiff
  - libwebp-base
  - libxml2
  - libxslt
  - libzlib
  - matplotlib
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - patsy
  - pcre2
  - pillow
  - pip
  - pyparsing
  - python=3.10.6
  - python-dateutil
  - python-tzdata
  - pytz
  - qt6-main
  - scikit-learn
  - seaborn
  - setuptools
  - six
  - statsmodels
  - tbb
  - threadpoolctl
  - tk
  - tornado
  - tzdata
  - wheel
  - xz
  - zstd
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiohttp-cors==0.8.0
      - aiosignal==1.3.2
      - ansicon==1.89.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blessed==1.20.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - colorful==0.5.6
      - cryptography==41.0.7
      - distlib==0.3.9
      - filelock==3.18.0
      - flwr==1.5.0
      - frozenlist==1.5.0
      - google-api-core==2.24.2
      - google-auth==2.38.0
      - googleapis-common-protos==1.69.2
      - gpustat==1.1.1
      - grpcio==1.71.0
      - hydra-core==1.3.2
      - idna==3.10
      - iterators==0.0.2
      - jinxed==1.3.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - msgpack==1.1.0
      - multidict==6.2.0
      - nvidia-ml-py==12.570.86
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - platformdirs==3.11.0
      - prometheus-client==0.21.1
      - propcache==0.3.0
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.0.0
      - py-spy==0.4.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydantic==1.10.21
      - pyyaml==6.0.2
      - ray==2.6.3
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.23.1
      - rsa==4.9
      - scipy==1.11.4
      - smart-open==7.1.0
      - torch==1.12.1
      - torch-cka==0.21
      - torchvision==0.13.1
      - tqdm==4.66.1
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - virtualenv==20.21.0
      - wcwidth==0.2.13
      - wrapt==1.12.1
      - yarl==1.18.3
