name: flwr-niid-bench
channels:
  - conda-forge
  - defaults
  - sebp
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.1.31=h56e8100_0
  - cairo=1.18.4=h5782bbf_0
  - contourpy=1.3.1=py310hc19bc0b_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py310h38315fa_0
  - freetype=2.13.3=h0b5ce68_0
  - graphite2=1.3.13=h63175ca_1003
  - harfbuzz=10.4.0=h9e37d49_0
  - icu=75.1=he0c23c2_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - joblib=1.4.2=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py310hc19bc0b_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=31_h641d27c_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=31_h5e41251_mkl
  - libclang13=20.1.1=default_ha5278ca_0
  - libdeflate=1.23=h9062f6e_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.6=h537db12_0
  - libgcc=14.2.0=h1383e82_2
  - libglib=2.82.2=h7025463_1
  - libgomp=14.2.0=h1383e82_2
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=31_h1aa476e_mkl
  - liblzma=5.6.4=h2466b09_0
  - liblzma-devel=5.6.4=h2466b09_0
  - libpng=1.6.47=had7236b_0
  - libsqlite=3.49.1=h67fdade_2
  - libtiff=4.7.0=h797046b_3
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.6=he286e8c_0
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - matplotlib=3.10.1=py310h5588dad_0
  - matplotlib-base=3.10.1=py310h37e0a56_0
  - mkl=2024.2.2=h66d3029_15
  - munkres=1.1.4=pyh9f0ad1d_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.4.1=ha4e3fda_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310hb4db72f_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h3d7b363_2
  - pillow=11.1.0=py310h9595edc_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=had0cd8c_0
  - pthread-stubs=0.4=h0e40799_1002
  - pyparsing=3.2.2=pyhd8ed1ab_0
  - pyside6=6.8.2=py310h60c6385_1
  - python=3.10.6=hcf16a7b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.8.2=h1259614_0
  - scikit-learn=1.6.1=py310hf2a6c47_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - statsmodels=0.14.4=py310hb0944cc_0
  - tbb=2021.13.0=h62715c5_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.2=py310ha8f682b_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py310ha8f682b_0
  - vc=14.3=hbf610ac_24
  - vc14_runtime=14.42.34438=hfd919c2_24
  - vs2015_runtime=14.42.34438=h7142326_24
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h208afaa_0
  - xz-tools=5.6.4=h2466b09_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiohttp-cors==0.8.0
      - aiosignal==1.3.2
      - ansicon==1.89.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blessed==1.20.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - colorful==0.5.6
      - cryptography==41.0.7
      - distlib==0.3.9
      - filelock==3.18.0
      - flwr==1.5.0
      - frozenlist==1.5.0
      - google-api-core==2.24.2
      - google-auth==2.38.0
      - googleapis-common-protos==1.69.2
      - gpustat==1.1.1
      - grpcio==1.71.0
      - hydra-core==1.3.2
      - idna==3.10
      - iterators==0.0.2
      - jinxed==1.3.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - msgpack==1.1.0
      - multidict==6.2.0
      - numpy==1.26.4
      - nvidia-ml-py==12.570.86
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - platformdirs==3.11.0
      - prometheus-client==0.21.1
      - propcache==0.3.0
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.0.0
      - py-spy==0.4.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydantic==1.10.21
      - pyyaml==6.0.2
      - ray==2.6.3
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.23.1
      - rsa==4.9
      - scipy==1.11.4
      - smart-open==7.1.0
      - torch==1.12.1
      - torch-cka==0.21
      - torchvision==0.13.1
      - tqdm==4.66.1
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - virtualenv==20.21.0
      - wcwidth==0.2.13
      - wrapt==1.12.1
      - yarl==1.18.3
prefix: C:\Users\AFreitas\AppData\Local\anaconda3\envs\flwr-niid-bench
